### ISSUE TITLE
Blocked-Commands participation not check queue

### ISSUE THREAD

**Issue by slvlr** [elian1203/ezAuctions#12]
Commands that cannot be executed while you are participating in an auction
Participants include the auctioneer and the bidders
Please do not include the '/' in the command
  blocked-commands:
    - 'ma'

I have set this up like above, which prevents players joining the mob arena while having an auction active (then when the auction ends with no bids, the item is given to them in the mob arena).
This works fine, however if there is an auction queue, it does not check that they are participating in the next auction, allowing them to join the arena, and then get their item after the next action.

Please could you fix this by checking if the player is also in an action queue?

**Comment by elian1203** [comment]
Per #13 players in auction queue will now also be blocked from executing the specified blocked commands in the config.yml file.
