### ISSUE TITLE
offline player items

### ISSUE THREAD

**Issue by waiching514** [elian1203/ezAuctions#25]
When a player offline and he got items from auction, because my server installed MySQL Player Data Bridge, they will losed their item from auction from MySQL Player Data Bridge sync backpack.

So I want to suggest adding a delay option or inventory from command to take auction item

auction item mean what they win (money or items) in the bid or on one bid items

**Comment by elian1203** [comment]
I would reach out to the developer of that plugin as that is an issue for them if it takes a while for the inventory to load and items are lost in the meantime. Even if I added a delay for the items it would be an arbitrary period of time and may work sometimes and other times could still be too quick depending on the connection to the database for your data bridge.
