### ISSUE TITLE
Updating to Support 1.19

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [elian1203/ezAuctions#26]
Could you please update it to support 1.19? Great plugin!

Error on 1.19 Paper:
https://pastebin.com/hcXq5Z5g

**Comment by elian1203** [comment]
Can you provide some more details regarding this error? This does not look like anything related to 1.19. Did this happen when you were shutting down the server? Do you use any plugins such as PlugMan or similar to load/unload plugins?

**Comment by elian1203** [comment]
This issue was resolved in #28.

It only occurred when running ezAuctions without installing vault/econ provider and the plugin would attempt to shut itself down. Spigot must have changed it to run the onDisable when a plugin self-disables.
