### ISSUE TITLE
Two errors updating to 2.2.1

### ISSUE THREAD

**Issue by FatherWh0** [elian1203/ezAuctions#52]
paper-1.20.2-307
ezauctions 2.2.1

I am upgrading to 1.20.2 on my test server so I'm upgrading directly from eza 1.7.0 to 2.2.1.
I am receiving a database error on load and a missing message key on use. Also, the formatting isn't working correctly in-game. Pls see links below.
https://prnt.sc/2M0IyIo8-h1Q
https://pastebin.com/nsMWYeZP

**Comment by elian1203** [comment]
There are some steps that need to be taken when upgrading to 2.0. See this ticket. #43
