### ISSUE TITLE
1.20.6 paper support 

### ISSUE THREAD

**Issue by Momshroom** [elian1203/ezAuctions#55]
Just making sure you're aware that this doesn't load on 1.20.6 paper (tested on builds 131 and 140):
https://paste.gg/p/Momshroom/26e33c3330a14025b1611b435f18e1c1

Thanks!

**Comment by silverwolfg11** [comment]
Hi, thanks for making us aware of this! Hopefully, this issue will be resolved by https://github.com/elian1203/ezAuctions/pull/56 . Please try out the jar attached, and report any issues with it on the pull-request. Thanks!
[ezAuctions.zip](https://github.com/user-attachments/files/15942031/ezAuctions.zip)

**Comment by Momshroom** [comment]
Hi!  Sorry for the very slow response, and thank you for the test jar.  
The jar works in that the plugin now loads without errors, but, even after regenerating the plugin folder, the messaging is very messed up:
https://prnt.sc/MlwZg43ZJzvE

Auctions do work, though.

**Comment by Momshroom** [comment]
fixed by replacing >:"" in messages.properties with >
as was suggested in #57
