### ISSUE TITLE
Item not show correct

### ISSUE THREAD

**Issue by MarcuriDev** [elian1203/ezAuctions#57]
Hello! 

I'm using the build for 1.21 that is given in https://github.com/elian1203/ezAuctions/issues/55

Item is not shown correctly.

auction.info={prefix}<yellow><hover:show_entity:player:"<auctioneeruuid>"><auctioneer></hover> <white>esta subastando <green><itemamount> <aqua><hover:show_item:<materialtype>:<itemamount>:""><hascustomname><i><customname></i></hascustomname><nocustomname><lang:<minecraftname>></nocustomname><skull> <green>(Head of <white><skullowner></white>)<green></skull></hover> <white>por <gold>$<highestbidamount> <white>y un incremento de <gold>$<increment> <white>durante <green><remainingtime> <white>segundos.\
  <unrepairable><newline><white>This item cannot be repaired.</unrepairable><repair><newLine><white>This item has a prior work penalty of <green><repairprice><white> levels.</repair>\
  <autobuy><newline><white>El autobuy de esta subasta esta colocado en<gold>$<autobuy><white></autobuy>\
  <sealed><newline><white>Esta es una subasta sellada. Las ofertas no serán reveladas.</sealed>

<img width="834" alt="Captura de pantalla 2024-07-09 a las 12 46 29" src="https://github.com/elian1203/ezAuctions/assets/20406803/cd2c80e4-6d39-4ac5-9d2e-388725c9f14f">

**Comment by silverwolfg11** [comment]
Hi, thanks for reporting this!

Please try deleting the empty quotes (`""`) from the `<hover:show_item:<materialtype>:<itemamount>:"">` section in the auction info message (`auction.info`) in the plugin's messages file (`messages.properties`).

**Comment by MarcuriDev** [comment]
Solved.

Thanks!!

**Comment by perlsol** [comment]
HI, I just found this issue, I have tried removing the empty quotes as advised above but I still get the problem...
![image](https://github.com/elian1203/ezAuctions/assets/6700023/0b5920e9-8a3d-4694-aad4-3452b3b4056a)
can you advise please, many thanks.

**Comment by perlsol** [comment]
I have checked everything I can think of to see what could be causing the above problem but have hit a brick wall, any feedback would be great, anythink anyone can think of to check please?

**Comment by perlsol** [comment]
please will you update this

**Comment by Momshroom** [comment]
This is fixed by the suggestion at the top, BUT you need to delete the :"" and not just "".
a find and replace for >:"" with > on the file fixes it perfectly (followed by an /auc reload)
