### ISSUE TITLE
Auctions of 100 or more items cause massive console error

### ISSUE THREAD

**Issue by Momshroom** [elian1203/ezAuctions#58]
On 1.21.1, paper 65 (Error also occurs on paper 52.  I've not tried other builds), and eZAuctions 2.2.3-1.20.6_support-SNAPSHOT (from my prior ticket), the plugin works fine auctioning 99 or fewer items, but when auctioning 100 or more, this a large console error appears and the information about the auction is not posted to chat.   Cancelling the auction with /auc c *does* return the items to the player.

Error:
https://paste.gg/p/Momshroom/bef5a414afdc4c42a811cba4a99dd9c3

**Comment by elian1203** [comment]
Thank you for reporting and submitting a pull request! This is available in version 2.2.3.
