### ISSUE TITLE
getCurrentAuction can be null

### ISSUE THREAD

**Issue by HSGamer** [elian1203/ezAuctions#9]
Line: https://github.com/elian1203/ezAuctions/blob/4c20c59e0583c40c91618d4bbd5c59f65e4dbb5c/src/main/java/net/urbanmc/ezauctions/listener/WorldChangeListener.java#L34
This will cause NPE if the player switches worlds when there is no auction.

**Comment by elian1203** [comment]
Good catch. Fixing.
